version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: ${PATH_TO_PROJECT}
      dockerfile: docker/Dockerfile-nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      sc_network:
        ipv4_address: 172.172.0.2
  server:
    container_name: server
    build:
      context: ${PATH_TO_PROJECT}
      dockerfile: docker/Dockerfile-go
    restart: always
    networks:
      sc_network:
        ipv4_address: 172.172.0.3
  app:
    container_name: app
    build:
      context: ${PATH_TO_PROJECT}
      dockerfile: docker/Dockerfile-nuxt
    restart: always
    networks:
      sc_network:
        ipv4_address: 172.172.0.4

networks:
  sc_network:
    name: sc_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.172.0.0/24
          gateway: 172.172.0.1